### ISSUE TITLE
No issues here - works perfectly

### ISSUE THREAD

**Issue by SolarSistim** [tylerforesthauser/Homebase#5]
Could not get Wamp or Apache running properly on my Window server, got Xamp and Homebase worked right out of the box. Minor issue with the transparent overlays on the Recently Added page, not complaining.

Just wanted to give the dev some props because this kinda brought together all my Plex services.

[http://tinypic.com/r/25h1i1c/9](url)

[http://tinypic.com/r/34ezyc6/9](url)

**Comment by tylerforesthauser** [comment]
Glad to hear it!
